### ISSUE TITLE
error unpacking APK

### ISSUE THREAD

**Issue by zitkon** [kefir500/apk-editor-studio#129]
this is error notice:
I: Using Apktool 2.7.0 on HARLEYMOD KR 64BIT VIP.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:294)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:49)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:292)
	... 3 more
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1736)
	at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1254)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1701)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1430)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1393)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:742)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:859)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:257)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:200)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more

thanks DEV

**Comment by ClarkKeyton** [comment]
.ZipException: Invalid CEN header - **It's Because APK is Obfuscated!!!**
