### ISSUE TITLE
Error while unpacking apk using this tool

### ISSUE THREAD

**Issue by cyb3rgh05t** [kefir500/apk-editor-studio#147]
Hi,

i am trying to unpack an apk using Apk Editor Studio with apktool 2.9.3 an java build 1.8.0_411-b09 an i get an error:

```
I: Using Apktool 2.9.3 on StreamNet.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\User\AppData\Local\apk-editor-studio\frameworks\1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" java.lang.IllegalArgumentException: expected namespace null and not 'http://schemas.android.com/apk/res/android'
	at org.xmlpull.renamed.MXSerializer.endTag(MXSerializer.java:697)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.endTag(XmlSerializerDelegate.java:124)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:215)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:78)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:137)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:149)
	at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:91)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:112)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
```
is there a way how i can resolve this?

**Comment by Ibuprophen** [comment]
This appears to be the same/similar issue as discussed on https://github.com/iBotPeaches/Apktool/issues/3027. 

@kefir500? 

~Ibuprophen

**Comment by kefir500** [comment]
Sorry for the delay.
Seems that you already have submitted the corresponding [issue](https://github.com/iBotPeaches/Apktool/issues/3583) in the Apktool repo, so we'll wait for the next Apktool release.
