### ISSUE TITLE
An error occurred while unpacking APK.

### ISSUE THREAD

**Issue by josep-001** [kefir500/apk-editor-studio#152]
`I: Using Apktool 2.9.3 on xxxxxxxx.apk
Exception in thread "main" brut.androlib.exceptions.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.androlib.apk.ApkInfo.hasResources(ApkInfo.java:88)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:98)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:49)
	at brut.androlib.apk.ApkInfo.hasResources(ApkInfo.java:86)
	... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more`

**Comment by kefir500** [comment]
Providing the APK file would be helpful.
