### ISSUE TITLE
Dex version 040 is not supported

### ISSUE THREAD

**Issue by JarJarBlinkz** [kefir500/apk-editor-studio#163]
Dex version 040 is not supported - UnsupportedFile Exception

Description:

I encountered an issue while trying to decompile an APK using ApkTool/Baksmali. The error message indicates that .dex version 040 is not supported, which prevents the tool from successfully decoding the APK.

Error Message:

I: Baksmaling classes.dex...
Exception in thread "main" com.android.tools.smali.dexlib2.util.DexUtil$UnsupportedFile: Dex version 040 is not supported
	at com.android.tools.smali.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:96)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.getVersion(DexBackedDexFile.java:172)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:199)
	at com.android.tools.smali.dexlib2.dexbacked.ZipDexContainer$1.getDexFile(ZipDexContainer.java:180)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:88)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:36)
	at brut.androlib.ApkDecoder.decodeSourcesSmali(ApkDecoder.java:220)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:127)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)

**Comment by kefir500** [comment]
Related Apktool issue: https://github.com/iBotPeaches/Apktool/issues/3562
Please, update the Apktool to the latest version via `Help` → `Check for Updates`.
