### ISSUE TITLE
Error unpacking APK

### ISSUE THREAD

**Issue by JIgar1055** [kefir500/apk-editor-studio#23]
after i select apk file show error as below screen shot. 

![image](https://user-images.githubusercontent.com/67065676/84920881-606b5b00-b0e1-11ea-8831-a8df2350b993.png)

**Comment by kefir500** [comment]
You should install [Java](https://java.com/en/download/) on your machine.

**Comment by xcdmmmmd01215** [comment]
i have the same Problem and i have java on my machine and android studio work with me

**Comment by xcdmmmmd01215** [comment]
so what is the problem ???

**Comment by kefir500** [comment]
@xcdmmmmd01215

APK Editor Studio tries to find Java in the following places:

- Path provided in the APK Editor Studio settings.
- Path from the `JAVA_HOME` environment variable.
- Path from the Windows registry.
- Path(s) from the `PATH` environment variable.

So, you can always set the Java path manually in the APK Editor Studio:
`Settings` → `Options` → `Java` → `Java path`

**Comment by linchpin89-smash-hit-modder** [comment]
I keep getting the error message in APK Editor Studio "I: Using Apktool 2.7.0 on smashhit2-v1.5.2-perfectmodsofficial.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:294)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:49)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:292)
	... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more"
